package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer addressId;
     private Employee employee;
     private String vaillage;
     private String upazilla;
     private String district;
     private String postCode;

    public Address() {
    }

    public Address(Employee employee, String vaillage, String upazilla, String district, String postCode) {
       this.employee = employee;
       this.vaillage = vaillage;
       this.upazilla = upazilla;
       this.district = district;
       this.postCode = postCode;
    }
   
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getVaillage() {
        return this.vaillage;
    }
    
    public void setVaillage(String vaillage) {
        this.vaillage = vaillage;
    }
    public String getUpazilla() {
        return this.upazilla;
    }
    
    public void setUpazilla(String upazilla) {
        this.upazilla = upazilla;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }




}


