package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private Integer AId;
     private Employee employee;
     private String empName;
     private Date date;
     private Integer present;
     private Integer absent;
     private Integer late;
     private String status;
     private Set srs = new HashSet(0);

    public Attendance() {
    }

    public Attendance(Employee employee, String empName, Date date, Integer present, Integer absent, Integer late, String status, Set srs) {
       this.employee = employee;
       this.empName = empName;
       this.date = date;
       this.present = present;
       this.absent = absent;
       this.late = late;
       this.status = status;
       this.srs = srs;
    }
   
    public Integer getAId() {
        return this.AId;
    }
    
    public void setAId(Integer AId) {
        this.AId = AId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getPresent() {
        return this.present;
    }
    
    public void setPresent(Integer present) {
        this.present = present;
    }
    public Integer getAbsent() {
        return this.absent;
    }
    
    public void setAbsent(Integer absent) {
        this.absent = absent;
    }
    public Integer getLate() {
        return this.late;
    }
    
    public void setLate(Integer late) {
        this.late = late;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getSrs() {
        return this.srs;
    }
    
    public void setSrs(Set srs) {
        this.srs = srs;
    }




}


