package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1



/**
 * BManager generated by hbm2java
 */
public class BManager  implements java.io.Serializable {


     private Integer bmId;
     private Employee employee;
     private Location location;
     private String bmName;

    public BManager() {
    }

    public BManager(Employee employee, Location location, String bmName) {
       this.employee = employee;
       this.location = location;
       this.bmName = bmName;
    }
   
    public Integer getBmId() {
        return this.bmId;
    }
    
    public void setBmId(Integer bmId) {
        this.bmId = bmId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getBmName() {
        return this.bmName;
    }
    
    public void setBmName(String bmName) {
        this.bmName = bmName;
    }




}


