package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1



/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private Integer DId;
     private Employee employee;
     private Location location;
     private Supplier supplier;
     private String DName;

    public Driver() {
    }

    public Driver(Employee employee, Location location, Supplier supplier, String DName) {
       this.employee = employee;
       this.location = location;
       this.supplier = supplier;
       this.DName = DName;
    }
   
    public Integer getDId() {
        return this.DId;
    }
    
    public void setDId(Integer DId) {
        this.DId = DId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getDName() {
        return this.DName;
    }
    
    public void setDName(String DName) {
        this.DName = DName;
    }




}


