package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer empId;
     private String empName;
     private String eamil;
     private String mobile;
     private String desgination;
     private Date hireDate;
     private Set drivers = new HashSet(0);
     private Set addresses = new HashSet(0);
     private Set saleses = new HashSet(0);
     private Set managers = new HashSet(0);
     private Set suppliers = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set suppervisors = new HashSet(0);
     private Set attendances = new HashSet(0);
     private Set BManagers = new HashSet(0);
     private Set locations = new HashSet(0);
     private Set ctrlAccesses = new HashSet(0);
     private Set salaries = new HashSet(0);

    public Employee() {
    }

    public Employee(String empName, String eamil, String mobile, String desgination, Date hireDate, Set drivers, Set addresses, Set saleses, Set managers, Set suppliers, Set logins, Set suppervisors, Set attendances, Set BManagers, Set locations, Set ctrlAccesses, Set salaries) {
       this.empName = empName;
       this.eamil = eamil;
       this.mobile = mobile;
       this.desgination = desgination;
       this.hireDate = hireDate;
       this.drivers = drivers;
       this.addresses = addresses;
       this.saleses = saleses;
       this.managers = managers;
       this.suppliers = suppliers;
       this.logins = logins;
       this.suppervisors = suppervisors;
       this.attendances = attendances;
       this.BManagers = BManagers;
       this.locations = locations;
       this.ctrlAccesses = ctrlAccesses;
       this.salaries = salaries;
    }
   
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public String getEamil() {
        return this.eamil;
    }
    
    public void setEamil(String eamil) {
        this.eamil = eamil;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getDesgination() {
        return this.desgination;
    }
    
    public void setDesgination(String desgination) {
        this.desgination = desgination;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public Set getDrivers() {
        return this.drivers;
    }
    
    public void setDrivers(Set drivers) {
        this.drivers = drivers;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }
    public Set getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set saleses) {
        this.saleses = saleses;
    }
    public Set getManagers() {
        return this.managers;
    }
    
    public void setManagers(Set managers) {
        this.managers = managers;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getSuppervisors() {
        return this.suppervisors;
    }
    
    public void setSuppervisors(Set suppervisors) {
        this.suppervisors = suppervisors;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }
    public Set getBManagers() {
        return this.BManagers;
    }
    
    public void setBManagers(Set BManagers) {
        this.BManagers = BManagers;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }
    public Set getCtrlAccesses() {
        return this.ctrlAccesses;
    }
    
    public void setCtrlAccesses(Set ctrlAccesses) {
        this.ctrlAccesses = ctrlAccesses;
    }
    public Set getSalaries() {
        return this.salaries;
    }
    
    public void setSalaries(Set salaries) {
        this.salaries = salaries;
    }




}


