package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer locId;
     private Employee employee;
     private String locName;
     private Set suppervisors = new HashSet(0);
     private Set srs = new HashSet(0);
     private Set BManagers = new HashSet(0);
     private Set drivers = new HashSet(0);
     private Set suppliers = new HashSet(0);

    public Location() {
    }

    public Location(Employee employee, String locName, Set suppervisors, Set srs, Set BManagers, Set drivers, Set suppliers) {
       this.employee = employee;
       this.locName = locName;
       this.suppervisors = suppervisors;
       this.srs = srs;
       this.BManagers = BManagers;
       this.drivers = drivers;
       this.suppliers = suppliers;
    }
   
    public Integer getLocId() {
        return this.locId;
    }
    
    public void setLocId(Integer locId) {
        this.locId = locId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getLocName() {
        return this.locName;
    }
    
    public void setLocName(String locName) {
        this.locName = locName;
    }
    public Set getSuppervisors() {
        return this.suppervisors;
    }
    
    public void setSuppervisors(Set suppervisors) {
        this.suppervisors = suppervisors;
    }
    public Set getSrs() {
        return this.srs;
    }
    
    public void setSrs(Set srs) {
        this.srs = srs;
    }
    public Set getBManagers() {
        return this.BManagers;
    }
    
    public void setBManagers(Set BManagers) {
        this.BManagers = BManagers;
    }
    public Set getDrivers() {
        return this.drivers;
    }
    
    public void setDrivers(Set drivers) {
        this.drivers = drivers;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }




}


