package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer userId;
     private Employee employee;
     private String userName;
     private String password;
     private Set ctrlAccesses = new HashSet(0);

    public Login() {
    }

    public Login(Employee employee, String userName, String password, Set ctrlAccesses) {
       this.employee = employee;
       this.userName = userName;
       this.password = password;
       this.ctrlAccesses = ctrlAccesses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCtrlAccesses() {
        return this.ctrlAccesses;
    }
    
    public void setCtrlAccesses(Set ctrlAccesses) {
        this.ctrlAccesses = ctrlAccesses;
    }




}


