package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private Integer MId;
     private Employee employee;
     private String MName;
     private Set suppervisors = new HashSet(0);

    public Manager() {
    }

    public Manager(Employee employee, String MName, Set suppervisors) {
       this.employee = employee;
       this.MName = MName;
       this.suppervisors = suppervisors;
    }
   
    public Integer getMId() {
        return this.MId;
    }
    
    public void setMId(Integer MId) {
        this.MId = MId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getMName() {
        return this.MName;
    }
    
    public void setMName(String MName) {
        this.MName = MName;
    }
    public Set getSuppervisors() {
        return this.suppervisors;
    }
    
    public void setSuppervisors(Set suppervisors) {
        this.suppervisors = suppervisors;
    }




}


