package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1



/**
 * Prices generated by hbm2java
 */
public class Prices  implements java.io.Serializable {


     private Integer pricesId;
     private String proName;
     private Double purPrice;
     private Double salesPrice;
     private Integer id;

    public Prices() {
    }

    public Prices(String proName, Double purPrice, Double salesPrice, Integer id) {
       this.proName = proName;
       this.purPrice = purPrice;
       this.salesPrice = salesPrice;
       this.id = id;
    }
   
    public Integer getPricesId() {
        return this.pricesId;
    }
    
    public void setPricesId(Integer pricesId) {
        this.pricesId = pricesId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public Double getPurPrice() {
        return this.purPrice;
    }
    
    public void setPurPrice(Double purPrice) {
        this.purPrice = purPrice;
    }
    public Double getSalesPrice() {
        return this.salesPrice;
    }
    
    public void setSalesPrice(Double salesPrice) {
        this.salesPrice = salesPrice;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


