package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Purchases generated by hbm2java
 */
public class Purchases  implements java.io.Serializable {


     private Integer purId;
     private Product product;
     private String purName;
     private String serialNo;
     private Date purchasesDate;
     private double price;
     private int quantity;
     private double totalPrice;

    public Purchases() {
    }

    public Purchases(Product product, String purName, String serialNo, Date purchasesDate, double price, int quantity, double totalPrice) {
       this.product = product;
       this.purName = purName;
       this.serialNo = serialNo;
       this.purchasesDate = purchasesDate;
       this.price = price;
       this.quantity = quantity;
       this.totalPrice = totalPrice;
    }
   
    public Integer getPurId() {
        return this.purId;
    }
    
    public void setPurId(Integer purId) {
        this.purId = purId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getPurName() {
        return this.purName;
    }
    
    public void setPurName(String purName) {
        this.purName = purName;
    }
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }
    public Date getPurchasesDate() {
        return this.purchasesDate;
    }
    
    public void setPurchasesDate(Date purchasesDate) {
        this.purchasesDate = purchasesDate;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }




}


