package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1



/**
 * Salary generated by hbm2java
 */
public class Salary  implements java.io.Serializable {


     private Integer salaryId;
     private Employee employee;
     private Sr sr;
     private String empName;
     private Double basicSalary;
     private Double target;
     private Double taDa;

    public Salary() {
    }

    public Salary(Employee employee, Sr sr, String empName, Double basicSalary, Double target, Double taDa) {
       this.employee = employee;
       this.sr = sr;
       this.empName = empName;
       this.basicSalary = basicSalary;
       this.target = target;
       this.taDa = taDa;
    }
   
    public Integer getSalaryId() {
        return this.salaryId;
    }
    
    public void setSalaryId(Integer salaryId) {
        this.salaryId = salaryId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Sr getSr() {
        return this.sr;
    }
    
    public void setSr(Sr sr) {
        this.sr = sr;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public Double getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(Double basicSalary) {
        this.basicSalary = basicSalary;
    }
    public Double getTarget() {
        return this.target;
    }
    
    public void setTarget(Double target) {
        this.target = target;
    }
    public Double getTaDa() {
        return this.taDa;
    }
    
    public void setTaDa(Double taDa) {
        this.taDa = taDa;
    }




}


