package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sales generated by hbm2java
 */
public class Sales  implements java.io.Serializable {


     private Integer salesId;
     private Employee employee;
     private Product product;
     private String proName;
     private Double price;
     private Integer quantity;
     private Double total;
     private Date sellDate;
     private Integer memoNo;

    public Sales() {
    }

    public Sales(Employee employee, Product product, String proName, Double price, Integer quantity, Double total, Date sellDate, Integer memoNo) {
       this.employee = employee;
       this.product = product;
       this.proName = proName;
       this.price = price;
       this.quantity = quantity;
       this.total = total;
       this.sellDate = sellDate;
       this.memoNo = memoNo;
    }
   
    public Integer getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(Integer salesId) {
        this.salesId = salesId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getSellDate() {
        return this.sellDate;
    }
    
    public void setSellDate(Date sellDate) {
        this.sellDate = sellDate;
    }
    public Integer getMemoNo() {
        return this.memoNo;
    }
    
    public void setMemoNo(Integer memoNo) {
        this.memoNo = memoNo;
    }




}


