package com.bs.pojo;
// Generated Sep 4, 2016 8:27:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sr generated by hbm2java
 */
public class Sr  implements java.io.Serializable {


     private Integer srId;
     private Attendance attendance;
     private Location location;
     private String srName;
     private Set salaries = new HashSet(0);

    public Sr() {
    }

    public Sr(Attendance attendance, Location location, String srName, Set salaries) {
       this.attendance = attendance;
       this.location = location;
       this.srName = srName;
       this.salaries = salaries;
    }
   
    public Integer getSrId() {
        return this.srId;
    }
    
    public void setSrId(Integer srId) {
        this.srId = srId;
    }
    public Attendance getAttendance() {
        return this.attendance;
    }
    
    public void setAttendance(Attendance attendance) {
        this.attendance = attendance;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getSrName() {
        return this.srName;
    }
    
    public void setSrName(String srName) {
        this.srName = srName;
    }
    public Set getSalaries() {
        return this.salaries;
    }
    
    public void setSalaries(Set salaries) {
        this.salaries = salaries;
    }




}


